site_name: 二进制漏洞挖掘与利用


pages:
  - 课程:
    - 目录: index.md
    - 课程介绍: buffer/intro.md
    - 背景与前提知识: buffer/background.md
    - 汇编语言与动态调试基础: buffer/assembly.md
    - 逆向基础: buffer/reverse_basis.md
    - 栈溢出: buffer/stack.md
    - 格式化字符串: buffer/format.md
    - Glibc堆分配机制: buffer/heap.md
    - 堆溢出的利用: buffer/heap-exp.md
    - ASLR与ASLR Bypass: buffer/aslr.md
    - DEP与DEP Bypass: buffer/DEP.md
  - 练习:
    - Linux安全基础:
      - linux1: nebula/1.md
      - linux2: nebula/2.md
      - linux3: nebula/3.md
      - linux4: nebula/4.md
      - linux5: nebula/5.md
    - ShellCode编写:
      - ShellCode编写入门: experiment/shellcode.md
    - 栈溢出:
      - stack1: prostar/stack0.md
      - stack2: prostar/stack2.md
      - stack3: prostar/stack4.md
      - stack4: prostar/stack6.md
    - 格式化字符串:
      - format1: prostar/format0.md
      - format2: prostar/format2.md
      - format3: prostar/format4.md
    - 堆溢出:
      - heap1: prostar/heap0.md
      - heap2: prostar/heap1.md
      - heap3: prostar/heap2.md
      - net1: prostar/net0.md
      - final1: prostar/final0.md
    - ARM架构漏洞利用:
      - ARM实验环境: experiment/arm1.md
      - ARM下shellcode开发: experiment/arm2.md
      - ARM栈溢出实验: experiment/arm3.md
      - ARM栈溢出实验进阶: experiment/arm3-2.md
      - ARM下编写tcp绑定shellcode: experiment/arm4.md
      - ARM下栈溢出实验: experiment/arm5.md
      - ARM下堆溢出实验: experiment/arm6.md
      - ARM下堆溢出实验进阶: experiment/arm7.md
    - Fuzzing:
      - AFL-Fuzz入门: afl/afl1.md
      - AFL-Fuzz进阶: afl/afl2.md
    - 其他:
      - PIN使用案例-PCTF2017: experiment/plaindctf2017_no_mo_flo.md
      - Android栈溢出攻击: experiment/android.md
      - 内核利用-环境配置: experiment/kernel.md




# Theme
theme:
  name: 'material'
  # custom_dir: 'theme'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'

extra_javascript:
  - '_static/js/extra.js'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
