site_name: My Docs 


pages: 
  - 课程:
    - Index: index.md
    - 缓冲区溢出漏洞: 
      - forward: buffer_overflow/forward.md
      - func: buffer_overflow/func.md
      - stack: buffer_overflow/stack.md
      - rop: buffer_overflow/rop.md
      - rop2: buffer_overflow/rop2.md
      - rop3: buffer_overflow/rop3.md
      - heap: buffer_overflow/heap.md
      - heap2: buffer_overflow/heap2.md
      - heap3: buffer_overflow/heap3.md
    - 其他漏洞:
      - format: none.md
      - format2: none.md
      - format3: none.md
      - intflow: none.md
      - 业务逻辑: none.md
      - 条件竞争: none.md
      - io_elf: none.md
      - io_elf2: none.md
    - fuzzing:
      - fuzz1: none.md
  - 实验: 
    - protostar: 
      - stack1: prostar/stack0.md
      - stack2: prostar/stack2.md
      - stack3: prostar/stack4.md
      - stack4: prostar/stack6.md
      - format1: prostar/format0.md
      - format2: prostar/format2.md


# Theme
theme:
  name: 'material'
  # custom_dir: 'theme'
  language: 'zh'
  palette:
    primary: 'white'
    accent: 'red'
  logo:
    icon: 'school'
  feature:
    tabs: true
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

# Customization
extra:
  search:
    language: 'jp'

extra_javascript:
  - '_static/js/extra.js'
  - 'https://cdn.bootcss.com/mathjax/2.7.2/MathJax.js?config=TeX-MML-AM_CHTML'

extra_css:
  - '_static/css/extra.css'

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
